[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
heartbeat = "arpxFMhub9LxVS5vE1gxVHTFKSFwE5QHakg5FvQv4Rt"
network = "EtPRQQTVAoq9cLwyHg54AHgGxjDaFDP6FYApCVwWB86o"
scheduler = "954gq7DotHyMPGJs57abBFJtGUn5iTRmFLUJgmbXwdck"

[programs.testnet]
heartbeat = "arpxFMhub9LxVS5vE1gxVHTFKSFwE5QHakg5FvQv4Rt"
network = "EtPRQQTVAoq9cLwyHg54AHgGxjDaFDP6FYApCVwWB86o"
scheduler = "954gq7DotHyMPGJs57abBFJtGUn5iTRmFLUJgmbXwdck"

[programs.mainnet]
heartbeat = "arpxFMhub9LxVS5vE1gxVHTFKSFwE5QHakg5FvQv4Rt"
network = "EtPRQQTVAoq9cLwyHg54AHgGxjDaFDP6FYApCVwWB86o"
scheduler = "954gq7DotHyMPGJs57abBFJtGUn5iTRmFLUJgmbXwdck"

[registry]
url = "https://anchor.projectserum.com"
