[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
heartbeat = "H7HagBMAbQCqSH6w7L5pmEGxo2WPdZpP81sjEjr2X6HV"
pool = "5fkWJPVaiCqtJgYx8MLgCxL3W8F4iYCn68mtdbsA37G1"
scheduler = "5GPxreRtDdv5qKLyhzDhwDQB9v227NVWCGb6AwNcv81B"

[registry]
url = "https://anchor.projectserum.com"
