[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
health = "Cbvb1VGjbno4N2dtixbVVPRP5vDUYFED2BZXN8zhJXEJ"
network = "6q8GGjwVtNjRRKHuUSGHLCvDM1FqkWaqsqDarrd4XfFX"
pool = "4e9CuABvghA9ep4jTbNfvdHUPuHApVV2xL4iWgGjE8xy"
scheduler = "7LxEojjkexSsyfrrPoUT78kBJPZXydR8RrkP1HixeD12"

[programs.testnet]
health = "Cbvb1VGjbno4N2dtixbVVPRP5vDUYFED2BZXN8zhJXEJ"
network = "6q8GGjwVtNjRRKHuUSGHLCvDM1FqkWaqsqDarrd4XfFX"
pool = "4e9CuABvghA9ep4jTbNfvdHUPuHApVV2xL4iWgGjE8xy"
scheduler = "7LxEojjkexSsyfrrPoUT78kBJPZXydR8RrkP1HixeD12"

[programs.mainnet]
health = "Cbvb1VGjbno4N2dtixbVVPRP5vDUYFED2BZXN8zhJXEJ"
network = "6q8GGjwVtNjRRKHuUSGHLCvDM1FqkWaqsqDarrd4XfFX"
pool = "4e9CuABvghA9ep4jTbNfvdHUPuHApVV2xL4iWgGjE8xy"
scheduler = "7LxEojjkexSsyfrrPoUT78kBJPZXydR8RrkP1HixeD12"

[registry]
url = "https://anchor.projectserum.com"
