[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
healthcheck = "BRF4V1gTsshYRwYZcqRBmRufaM5MtSfXR35p2RgU93az"
network = "EYRwKJVqWfnAa6Y3KxzfQDj9kgGqcqRp19hUxkkizGZn"
pool = "VDDnDnjt6fmqY4zXBNhxobJjbWBojArRPq6tu867t5k"
scheduler = "4Sun5bUmLrAosPF2iDjrbXBfupE5keYbRgM7ixYt8FfK"

[programs.testnet]
healthcheck = "BRF4V1gTsshYRwYZcqRBmRufaM5MtSfXR35p2RgU93az"
network = "EYRwKJVqWfnAa6Y3KxzfQDj9kgGqcqRp19hUxkkizGZn"
pool = "VDDnDnjt6fmqY4zXBNhxobJjbWBojArRPq6tu867t5k"
scheduler = "4Sun5bUmLrAosPF2iDjrbXBfupE5keYbRgM7ixYt8FfK"

[programs.mainnet]
healthcheck = "BRF4V1gTsshYRwYZcqRBmRufaM5MtSfXR35p2RgU93az"
network = "EYRwKJVqWfnAa6Y3KxzfQDj9kgGqcqRp19hUxkkizGZn"
pool = "VDDnDnjt6fmqY4zXBNhxobJjbWBojArRPq6tu867t5k"
scheduler = "4Sun5bUmLrAosPF2iDjrbXBfupE5keYbRgM7ixYt8FfK"

[registry]
url = "https://anchor.projectserum.com"
