[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
crank = "2mhQcnHhWuHyBbuf7GQUpD69Aq9JBLGa4bsa2WbWUAVT"
http = "Fbg9HZFafLy39Hfmj5346kPCarZy9WDxk8ADwFTUojF3"
network = "7uTtwxSLrUs6rTWzqYnvoQ8JnmcWT9WPDdoN1ojmvD6t"
pool = "CZZNnqWESL8qvcYktJ244YZo79L12g7EpJf646NgnKkb"

[programs.testnet]
crank = "2mhQcnHhWuHyBbuf7GQUpD69Aq9JBLGa4bsa2WbWUAVT"
http = "Fbg9HZFafLy39Hfmj5346kPCarZy9WDxk8ADwFTUojF3"
network = "7uTtwxSLrUs6rTWzqYnvoQ8JnmcWT9WPDdoN1ojmvD6t"
pool = "CZZNnqWESL8qvcYktJ244YZo79L12g7EpJf646NgnKkb"

[programs.mainnet]
crank = "2mhQcnHhWuHyBbuf7GQUpD69Aq9JBLGa4bsa2WbWUAVT"
http = "Fbg9HZFafLy39Hfmj5346kPCarZy9WDxk8ADwFTUojF3"
network = "7uTtwxSLrUs6rTWzqYnvoQ8JnmcWT9WPDdoN1ojmvD6t"
pool = "CZZNnqWESL8qvcYktJ244YZo79L12g7EpJf646NgnKkb"

[registry]
url = "https://anchor.projectserum.com"
