[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
health = "G4x3FhGgiQc6e9amuwXgYXHvuyboo7qgjDjNwto9m7TE"
network = "8Xvfudn1CCBCYwXaXsFUP9rVNJrCFxAfvy8ZVJqWQYHE"
pool = "GWnnYBp4yS7iAtLdh2wruCaD3aZqcuSp1iG83HtjCG4R"
scheduler = "4voyey7QaqxLgYTzY35pXbJGyib9M3Ty2p1Ss4qGx4YB"

[programs.testnet]
health = "G4x3FhGgiQc6e9amuwXgYXHvuyboo7qgjDjNwto9m7TE"
network = "8Xvfudn1CCBCYwXaXsFUP9rVNJrCFxAfvy8ZVJqWQYHE"
pool = "GWnnYBp4yS7iAtLdh2wruCaD3aZqcuSp1iG83HtjCG4R"
scheduler = "4voyey7QaqxLgYTzY35pXbJGyib9M3Ty2p1Ss4qGx4YB"

[programs.mainnet]
health = "G4x3FhGgiQc6e9amuwXgYXHvuyboo7qgjDjNwto9m7TE"
network = "8Xvfudn1CCBCYwXaXsFUP9rVNJrCFxAfvy8ZVJqWQYHE"
pool = "GWnnYBp4yS7iAtLdh2wruCaD3aZqcuSp1iG83HtjCG4R"
scheduler = "4voyey7QaqxLgYTzY35pXbJGyib9M3Ty2p1Ss4qGx4YB"

[registry]
url = "https://anchor.projectserum.com"
