[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
heartbeat = ""
pool = ""
scheduler = ""

[programs.testnet]
heartbeat = ""
pool = ""
scheduler = ""

[programs.mainnet]
heartbeat = ""
pool = ""
scheduler = ""

[registry]
url = "https://anchor.projectserum.com"
