[provider]
cluster = "devnet"
wallet = "/Users/garfield/.config/solana/id.json"

[programs.localnet]
cronos = "AUDt6tUdA3eMNjX5pyirrroNLyqupKUnzpeFdsrGBWmv"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 programs/**/client/src/*.test.ts"
