[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
health = "Ag6ZjQ1eFHAf1YYD3oaQnQ4KbrCAMqrSDBmY8o24KVTh"
http = "EB3Fb197CbjZtdzXVPLKpDapwpWju7JFPtGoSr82BFVe"
network = "BkKrMFDoZPyBxZ1W9S2XM8RdMK3Jjxttu33fXmVuybzd"
pool = "J1oQ8GLQDJBXrRmRWZ59XV47U9bCyib9ZJ6256EGgXmy"
scheduler = "8jb7Qt5izxLMGH1PNfGvtmqbzqDmue1zmfNrpwc2L8zL"

[programs.testnet]
health = "Ag6ZjQ1eFHAf1YYD3oaQnQ4KbrCAMqrSDBmY8o24KVTh"
http = "EB3Fb197CbjZtdzXVPLKpDapwpWju7JFPtGoSr82BFVe"
network = "BkKrMFDoZPyBxZ1W9S2XM8RdMK3Jjxttu33fXmVuybzd"
pool = "J1oQ8GLQDJBXrRmRWZ59XV47U9bCyib9ZJ6256EGgXmy"
scheduler = "8jb7Qt5izxLMGH1PNfGvtmqbzqDmue1zmfNrpwc2L8zL"

[programs.mainnet]
health = "Ag6ZjQ1eFHAf1YYD3oaQnQ4KbrCAMqrSDBmY8o24KVTh"
http = "EB3Fb197CbjZtdzXVPLKpDapwpWju7JFPtGoSr82BFVe"
network = "BkKrMFDoZPyBxZ1W9S2XM8RdMK3Jjxttu33fXmVuybzd"
pool = "J1oQ8GLQDJBXrRmRWZ59XV47U9bCyib9ZJ6256EGgXmy"
scheduler = "8jb7Qt5izxLMGH1PNfGvtmqbzqDmue1zmfNrpwc2L8zL"

[registry]
url = "https://anchor.projectserum.com"
