[provider]
cluster = "devnet"
wallet = "/Users/garfield/.config/solana/id.json"

[programs.localnet]
cronos = "5SXHntQ3KcnXVHd9dkrMhxuwwuNcX9TqcML68DHd8kKx"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 client/src/*.test.ts"
