[provider]
cluster = "devnet"
wallet = "/Users/garfield/.config/solana/id.json"

[programs.localnet]
cronos = "4BrFhSiCd38uv8gdkv866cy7D3rq39i3ugK3fgXaA5W3"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 client/src/*.test.ts"
