[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
health = "EtT6HekyRnbNf2hYjwPUy4tzFtJeNFUNcEwvZ7zWTPJW"
http = "7XuJ47K8yAuc27W99LMb7x4bUqSPhBDh6wiDRjHFK9rD"
network = "DvHjju2r7SGJjfcFYxwQi7abgSBgA5J9bkPXByxeus8g"
pool = "74txrgZch3YkKSTv1iFmLMw74QGkr4BPZfbapokHVWnD"
scheduler = "DWqfRsKR19LyLTwsntguu22aRvLFeY8ADSqcqpmLrAD"

[programs.testnet]
health = "EtT6HekyRnbNf2hYjwPUy4tzFtJeNFUNcEwvZ7zWTPJW"
http = "7XuJ47K8yAuc27W99LMb7x4bUqSPhBDh6wiDRjHFK9rD"
network = "DvHjju2r7SGJjfcFYxwQi7abgSBgA5J9bkPXByxeus8g"
pool = "74txrgZch3YkKSTv1iFmLMw74QGkr4BPZfbapokHVWnD"
scheduler = "DWqfRsKR19LyLTwsntguu22aRvLFeY8ADSqcqpmLrAD"

[programs.mainnet]
health = "EtT6HekyRnbNf2hYjwPUy4tzFtJeNFUNcEwvZ7zWTPJW"
http = "7XuJ47K8yAuc27W99LMb7x4bUqSPhBDh6wiDRjHFK9rD"
network = "DvHjju2r7SGJjfcFYxwQi7abgSBgA5J9bkPXByxeus8g"
pool = "74txrgZch3YkKSTv1iFmLMw74QGkr4BPZfbapokHVWnD"
scheduler = "DWqfRsKR19LyLTwsntguu22aRvLFeY8ADSqcqpmLrAD"

[registry]
url = "https://anchor.projectserum.com"
