[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
cronos = "B9d3x3owH4F3cX8fF18EVvr35xpRsACa5xJgDzEeVgsN"
pool = "CPfZ1wMDn7coZeaqGj7gmKyHAysC2NzkNYhMVpTYd8SS"

[registry]
url = "https://anchor.projectserum.com"
