[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
cronos = "CronpZj5NbHj2Nb6WwEtf6A9anty9JfEQ1RnGoshQBaW"
pool = "EKpcZk331JDfGaetHvU1LuUmDCh4Pv3392sfNZYt8gbQ"

[registry]
url = "https://anchor.projectserum.com"
