[provider]
cluster = "localnet"
wallet = "/Users/garfield/.config/solana/id.json"

[programs.localnet]
cronos = "5F5bYKuGwR5xrXr6mCo5wi6zAiSebSM2jzeDA8dwTF6A"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 client/src/*.test.ts"
