[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
health = "Ad3QowCe3o6oPTw4RHYVcEuuj2Cdmz64VR4gmjXJQAdk"
network = "tWPS21VQNakkr6BQpF6aZGqq9XJfdSN4gQSx5DrGs6z"
pool = "DuThutjVqp1a3BDxG78anLUVf6Q6r2cCrtWfNhvy5j25"
scheduler = "6FoQJ1cwnEt5pcNYBXAgYTrTnMr9eoJ4jYkBsc6hYKxx"

[programs.testnet]
health = "Ad3QowCe3o6oPTw4RHYVcEuuj2Cdmz64VR4gmjXJQAdk"
network = "tWPS21VQNakkr6BQpF6aZGqq9XJfdSN4gQSx5DrGs6z"
pool = "DuThutjVqp1a3BDxG78anLUVf6Q6r2cCrtWfNhvy5j25"
scheduler = "6FoQJ1cwnEt5pcNYBXAgYTrTnMr9eoJ4jYkBsc6hYKxx"

[programs.mainnet]
health = "Ad3QowCe3o6oPTw4RHYVcEuuj2Cdmz64VR4gmjXJQAdk"
network = "tWPS21VQNakkr6BQpF6aZGqq9XJfdSN4gQSx5DrGs6z"
pool = "DuThutjVqp1a3BDxG78anLUVf6Q6r2cCrtWfNhvy5j25"
scheduler = "6FoQJ1cwnEt5pcNYBXAgYTrTnMr9eoJ4jYkBsc6hYKxx"

[registry]
url = "https://anchor.projectserum.com"
