[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
heartbeat = "2ysCzNg41B2FSnjHqcyRVdrzf9d2pazqLARrb2qDJpbF"
network = "5Xu6iNDMf17wVC6aSoKeQsjF87aTQjrqpA9sX3sA5VJX"
scheduler = "FgaywchEfqzBcDVp8Eprf2jg6tv4Z3ptpahfHa15Eg6G"

[programs.testnet]
heartbeat = "2ysCzNg41B2FSnjHqcyRVdrzf9d2pazqLARrb2qDJpbF"
network = "5Xu6iNDMf17wVC6aSoKeQsjF87aTQjrqpA9sX3sA5VJX"
scheduler = "FgaywchEfqzBcDVp8Eprf2jg6tv4Z3ptpahfHa15Eg6G"

[programs.mainnet]
heartbeat = "2ysCzNg41B2FSnjHqcyRVdrzf9d2pazqLARrb2qDJpbF"
network = "5Xu6iNDMf17wVC6aSoKeQsjF87aTQjrqpA9sX3sA5VJX"
scheduler = "FgaywchEfqzBcDVp8Eprf2jg6tv4Z3ptpahfHa15Eg6G"

[registry]
url = "https://anchor.projectserum.com"
