[provider]
cluster = "devnet"
wallet = "/Users/garfield/.config/solana/id.json"

[programs.localnet]
cronos = "HGwuQXkzJKSAKQWinUZ2wX82M1AmHPchFYCHDNsNc7Yd"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 client/src/*.test.ts"
