[package]
name = "cronos-cli"
version = "0.0.6"
description = "Command line instruction scheduler for Solana"
edition = "2021"
license = "Apache-2.0"
homepage = "https://cronos.so"
repository = "https://github.com/cronos-so/cli"
documentation = "https://docs.cronos.so"
readme = "./README.md"
keywords = ["solana", "cronos", "cli"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anchor-lang = "0.20.1"
clap = { version = "3.0.14", features = ["derive"] }
cronos-sdk = "0.0.15"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
solana-account-decoder = "1.9.5"
solana-clap-utils = "1.9.5"
solana-cli-config = "1.9.5"
solana-client = "1.9.5"
solana-client-helpers = "1.1.0"
solana-remote-wallet = "1.9.5"
solana-sdk = "1.9.5"
spl-memo = "3.0.1"
thiserror = "1.0.30"

[[bin]]
name = "cronos"
path = "src/main.rs"
