[package]
name = "cronos_geyser_plugin"
description = "Geyser Plugin for Cronos"
authors = ["Cronos"]
version = "0.0.1"
edition = "2021"
repository = "https://github.com/cronos-so/plugin"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
prost = "0.9"
solana-accountsdb-plugin-interface = { version = "1.9.9" }
solana-logger = { version = "1.9.9" }
solana-program = { version = "1.9.9" }
log = "0.4"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
simple-error = "0.2.3"
cronos-sdk = "0.1.8"
solana-sdk = "=1.9.9"
bs58 = "0.4.0"
thiserror = "1.0.30"

[build-dependencies]
prost-build = "0.9"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
