[package]
name = "cron"
version = "0.2.0"
authors = ["Zack Slayton <zack.slayton@gmail.com>"]
repository = "https://github.com/zslayton/cron"
readme = "README.md"
description = "A cron expression parser in Rust."
keywords = [ "cron", "schedule", "repeat", "periodic", "time" ]
license = "MIT"

[lib]
name = "cron"

[dependencies]
chrono = "~0.3"
nom = "~2.1"
error-chain="~0.10.0"
