[workspace]
members = [
    "cli",
    "client",
    "cron",
    "metrics",
    "plugin",
    "programs/*",
    "stress"
]

[patch.crates-io]
anchor-lang = { git = "https://github.com/cronos-so/anchor", branch = "v0.24.2-solana.1.10.19" }
anchor-spl = { git = "https://github.com/cronos-so/anchor", branch = "v0.24.2-solana.1.10.19" }
