[package]
name = "cronos-bot"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anchor-lang = "0.20.1"
cronos-sdk = "0.0.16"
dotenv = "0.15.0"
postgres = "0.19.2"
solana-account-decoder = "1.9.5"
solana-client = "1.9.5"
solana-client-helpers = "1.1.0"
solana-sdk = "1.9.5"
ttl_cache = "0.5.1"
