[package]
name = "cronos-sdk"
version = "0.0.3"
edition = "2021"
description = "Created with Anchor"
license = "ISC"
homepage = "https://cronos.so"
repository = "https://github.com/cronos-so/sdk"
documentation = "https://docs.rs/cronos-sdk"
readme = "./README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anchor-client = { version = "0.20.1", features = ["debug"] }
cronos-program = { version = "0.0.8", features = ["no-entrypoint"] }
solana-program = "1.9.5"
