[package]
name = "cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anchor-lang = "0.20.1"
clap = { version = "3.0.14", features = ["derive"] }
cronos-sdk = "0.0.9"
solana-account-decoder = "1.9.5"
solana-clap-utils = "1.9.5"
solana-cli-config = "1.9.5"
solana-client = "1.9.5"
solana-client-helpers = "1.1.0"
solana-remote-wallet = "1.9.5"
solana-sdk = "1.9.5"
thiserror = "1.0.30"

