[package]
name = "cronos-telemetry"
version = "0.1.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cronos-sdk = { path = "../sdk", version = "0.1.6" }
dotenv = "0.15.0"
solana-account-decoder = "1.9.9"
solana-client = "1.9.9"
solana-sdk = "1.9.9"
solana-client-helpers = "1.1.0"
