[package]
name = "cronos-scheduler"
version = "0.2.0-alpha1"
description = "Cronos scheduling protocol"
edition = "2021"
license = "AGPL-3.0-or-later"
homepage = "https://cronos.so"
repository = "https://github.com/cronos-so/cronos"
documentation = "https://docs.cronos.so"
readme = "./README.md"
keywords = ["solana"]

[lib]
crate-type = ["cdylib", "lib"]
name = "cronos_scheduler"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.24.2"
chrono = { version = "0.4.19", default-features = false, features = ["alloc"] }
cronos-cron = { path = "../../cron", version = "0.2.0-alpha1" }
cronos-pool = { path = "../pool", features = ["cpi"], version = "0.2.0-alpha1" }
