[package]
name = "cronos-scheduler"
version = "0.1.8"
description = "A task scheduling protocol for Solana"
edition = "2021"
license = "Apache-2.0"
homepage = "https://cronos.so"
repository = "https://github.com/cronos-so/cronos"
documentation = "https://docs.cronos.so"
readme = "./README.md"
keywords = ["solana", "cronos", "program"]

[lib]
crate-type = ["cdylib", "lib"]
name = "cronos_scheduler"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "=0.22.0"
chrono = { version = "0.4.19", default-features = false, features = ["alloc"] }
cronos-cron = { path = "../../cron", version = "0.1.8" }
solana-program = "=1.9.9"
