[package]
name = "cronos-scheduler"
version = "0.1.8"
description = "Cronos scheduling protocol"
edition = "2021"
license = "GNU AGPLv3"
homepage = "https://cronos.so"
repository = "https://github.com/cronos-so/cronos"
documentation = "https://docs.cronos.so"
readme = "./README.md"
keywords = ["solana"]

[lib]
crate-type = ["cdylib", "lib"]
name = "cronos_scheduler"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = { git = "https://github.com/cronos-so/anchor", branch = "v0.24.2-solana.1.10.8" }
chrono = { version = "0.4.19", default-features = false, features = ["alloc"] }
cronos-cron = { path = "../../cron", version = "0.1.8" }
