[package]
name = "cronos-sdk"
version = "0.1.8"
edition = "2021"
description = "Cronos SDK"
license = "GNU AGPLv3"
homepage = "https://cronos.so"
repository = "https://github.com/cronos-so/sdk"
documentation = "https://docs.rs/cronos-sdk"
readme = "./README.md"
keywords = ["solana"]

[lib]
crate-type = ["cdylib", "lib"]
name = "cronos_sdk"

[dependencies]
anchor-lang = { git = "https://github.com/cronos-so/anchor", branch = "v0.24.2-solana.1.10.8" }
anchor-spl = { features = ["mint", "token"], git = "https://github.com/cronos-so/anchor", branch = "v0.24.2-solana.1.10.8" }
bincode = "1.3.3"
cronos-healthcheck = { path = "../programs/healthcheck", features = ["no-entrypoint"], version = "0.1.8" }
cronos-network = { path = "../programs/network", features = ["no-entrypoint"], version = "0.1.8" }
cronos-pool = { path = "../programs/pool", features = ["no-entrypoint"], version = "0.1.8" }
cronos-scheduler = { path = "../programs/scheduler", features = ["no-entrypoint"], version = "0.1.8" }
solana-client = "1.10.8"
solana-sdk = "1.10.8"
thiserror = "1.0.31"

[features]
client = []
