[package]
name = "cronos-sdk"
version = "0.1.5"
edition = "2021"
description = "Cronos program Rust client"
license = "Apache-2.0"
homepage = "https://cronos.so"
repository = "https://github.com/cronos-so/sdk"
documentation = "https://docs.rs/cronos-sdk"
readme = "./README.md"
keywords = ["solana", "cronos", "sdk"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anchor-client = { version = "0.22.0", features = ["debug"] }
cronos-program = { path = "../programs/cronos", features = ["no-entrypoint"], version = "0.1.5" }
solana-client-helpers = "1.1.0"
solana-program = "1.9.5"
solana-sdk = "1.9.8"
