[package]
name = "cronos-sdk"
version = "0.2.0-alpha2"
edition = "2021"
description = "Cronos SDK"
license = "AGPL-3.0-or-later"
homepage = "https://cronos.so"
repository = "https://github.com/cronos-so/sdk"
documentation = "https://docs.rs/cronos-sdk"
readme = "./README.md"
keywords = ["solana"]

[lib]
crate-type = ["cdylib", "lib"]
name = "cronos_sdk"

[dependencies]
anchor-lang = "0.24.2"
anchor-spl = { features = ["mint", "token"], version = "0.24.2" }
bincode = "1.3.3"
cronos-health = { path = "../programs/health", features = ["no-entrypoint"], version = "0.2.0-alpha2" }
cronos-network = { path = "../programs/network", features = ["no-entrypoint"], version = "0.2.0-alpha2" }
cronos-pool = { path = "../programs/pool", features = ["no-entrypoint"], version = "0.2.0-alpha2" }
cronos-scheduler = { path = "../programs/scheduler", features = ["no-entrypoint"], version = "0.2.0-alpha2" }
solana-client = "1.10.19"
solana-sdk = "1.10.19"
thiserror = "1.0.31"

[features]
client = []
