[package]
name = "cronos-sdk"
version = "0.1.8"
edition = "2021"
description = "Cronos program Rust client"
license = "Apache-2.0"
homepage = "https://cronos.so"
repository = "https://github.com/cronos-so/sdk"
documentation = "https://docs.rs/cronos-sdk"
readme = "./README.md"
keywords = ["solana", "cronos", "sdk"]

[lib]
crate-type = ["cdylib", "lib"]
name = "cronos_sdk"

[dependencies]
anchor-client = "=0.22.0"
cronos-program = { path = "../programs/cronos", features = ["no-entrypoint"], version = "0.1.8" }
solana-account-decoder = "=1.9.9"
solana-client = "=1.9.9"
solana-client-helpers = "1.1.0"
solana-program = "=1.9.9"
solana-sdk = "=1.9.9"
