name: Soteria Audit

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    container: solanalabs/solana:v1.10.8
    steps:
      - name: Check-out the repository
        uses: actions/checkout@v3
      - name: Soteria Audit
        continue-on-error: false
        uses: silas-x/soteria-action@main
        with:
          solana-version: "1.10.8"
          run-mode: "-analyzeAll"
          cargo-com: "."
          program-path: "."
