name: Soteria Audit

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out the repository
        uses: actions/checkout@v2
      - name: Soteria Audit
        continue-on-error: false
        uses: silas-x/soteria-action@main
        with:
          solana-version: "1.10.8"
          run-mode: "-analyzeAll"
          cargo-com: "."
          program-path: "."
