name: Audit

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    container: cronoslabs/dev:v1.10.8
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: List rustup toolchains
        run: rustup toolchain list
      - name: Set default toolchain
        run: rustup default stable
      - name: Cargo build
        run: cargo build
      - name: Soteria audit
        run: soteria -analyzeAll .
