name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: cronoslabs/dev:v1.10.8
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Set rust toolchain
        run: rustup toolchain list && rustup default stable && rustup toolchain list
      - name: Cargo build
        run: cargo build
