name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: solanalabs/solana:beta
    steps:
      - uses: actions/checkout@v3
      - name: Set default toolchain
        run: rustup default stable
      - name: Cargo build
        run: cargo build
