name: Anchor Build

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Remove Cargo Lock for fresh build
        run: rm -rf Cargo.Lock
        shell: bash
      - uses: actions/checkout@v3
      - uses: mrgnlabs/anchor-build-action@v0.3
