[package]
name = "cronos-metrics"
version = "0.2.0-alpha1"
description = "Performance monitoring for Cronos clusters"
edition = "2021"
license = "GNU AGPLv3"
homepage = "https://cronos.so"
repository = "https://github.com/cronos-so/cli"
documentation = "https://docs.cronos.so"
readme = "./README.md"
keywords = ["solana"]

[dependencies]
chrono = "0.4.19"
cronos-sdk = { path = "../sdk", features = ["client"], version = "0.2.0-alpha1" }
dotenv = "0.15.0"
elasticsearch = "7.14.0-alpha.1"
serde_json = "~1"
solana-client = "1.10.8"
solana-program = "1.10.8"
solana-sdk = "1.10.8"
tokio = { version = "1.17.0", features = ["full"] }
